# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/aksle/Downloads/Telegram Desktop/S3_19_Anderson Leong Ke Sheng_Bui Quang Huy_Archive/Wk8/Wk8.cache/wt} [current_project]
set_property parent.project_path {C:/Users/aksle/Downloads/Telegram Desktop/S3_19_Anderson Leong Ke Sheng_Bui Quang Huy_Archive/Wk8/Wk8.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo {c:/Users/aksle/Downloads/Telegram Desktop/S3_19_Anderson Leong Ke Sheng_Bui Quang Huy_Archive/Wk8/Wk8.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  {C:/Users/aksle/Downloads/Telegram Desktop/S3_19_Anderson Leong Ke Sheng_Bui Quang Huy_Archive/Wk8/Wk8.srcs/sources_1/new/Audio_Capture.v}
  {C:/Users/aksle/Downloads/Telegram Desktop/S3_19_Anderson Leong Ke Sheng_Bui Quang Huy_Archive/Wk8/Wk8.srcs/sources_1/new/Gameone.v}
  {C:/Users/aksle/Downloads/Telegram Desktop/S3_19_Anderson Leong Ke Sheng_Bui Quang Huy_Archive/Wk8/Wk8.srcs/sources_1/new/Oled_Display.v}
  {C:/Users/aksle/Downloads/Telegram Desktop/S3_19_Anderson Leong Ke Sheng_Bui Quang Huy_Archive/Wk8/Wk8.srcs/sources_1/new/anode_control.v}
  {C:/Users/aksle/Downloads/Telegram Desktop/S3_19_Anderson Leong Ke Sheng_Bui Quang Huy_Archive/Wk8/Wk8.srcs/sources_1/new/background.v}
  {C:/Users/aksle/Downloads/Telegram Desktop/S3_19_Anderson Leong Ke Sheng_Bui Quang Huy_Archive/Wk8/Wk8.srcs/sources_1/new/clk20k.v}
  {C:/Users/aksle/Downloads/Telegram Desktop/S3_19_Anderson Leong Ke Sheng_Bui Quang Huy_Archive/Wk8/Wk8.srcs/sources_1/new/game_background.v}
  {C:/Users/aksle/Downloads/Telegram Desktop/S3_19_Anderson Leong Ke Sheng_Bui Quang Huy_Archive/Wk8/Wk8.srcs/sources_1/new/game_mix.v}
  {C:/Users/aksle/Downloads/Telegram Desktop/S3_19_Anderson Leong Ke Sheng_Bui Quang Huy_Archive/Wk8/Wk8.srcs/sources_1/new/gameover.v}
  {C:/Users/aksle/Downloads/Telegram Desktop/S3_19_Anderson Leong Ke Sheng_Bui Quang Huy_Archive/Wk8/Wk8.srcs/sources_1/new/gametwo.v}
  {C:/Users/aksle/Downloads/Telegram Desktop/S3_19_Anderson Leong Ke Sheng_Bui Quang Huy_Archive/Wk8/Wk8.srcs/sources_1/new/gametwo_bg.v}
  {C:/Users/aksle/Downloads/Telegram Desktop/S3_19_Anderson Leong Ke Sheng_Bui Quang Huy_Archive/Wk8/Wk8.srcs/sources_1/new/ghost.v}
  {C:/Users/aksle/Downloads/Telegram Desktop/S3_19_Anderson Leong Ke Sheng_Bui Quang Huy_Archive/Wk8/Wk8.srcs/sources_1/new/grave.v}
  {C:/Users/aksle/Downloads/Telegram Desktop/S3_19_Anderson Leong Ke Sheng_Bui Quang Huy_Archive/Wk8/Wk8.srcs/sources_1/new/man.v}
  {C:/Users/aksle/Downloads/Telegram Desktop/S3_19_Anderson Leong Ke Sheng_Bui Quang Huy_Archive/Wk8/Wk8.srcs/sources_1/new/o_led_ctrls.v}
  {C:/Users/aksle/Downloads/Telegram Desktop/S3_19_Anderson Leong Ke Sheng_Bui Quang Huy_Archive/Wk8/Wk8.srcs/sources_1/new/rain.v}
  {C:/Users/aksle/Downloads/Telegram Desktop/S3_19_Anderson Leong Ke Sheng_Bui Quang Huy_Archive/Wk8/Wk8.srcs/sources_1/new/rainH.v}
  {C:/Users/aksle/Downloads/Telegram Desktop/S3_19_Anderson Leong Ke Sheng_Bui Quang Huy_Archive/Wk8/Wk8.srcs/sources_1/new/rainL.v}
  {C:/Users/aksle/Downloads/Telegram Desktop/S3_19_Anderson Leong Ke Sheng_Bui Quang Huy_Archive/Wk8/Wk8.srcs/sources_1/new/rainM.v}
  {C:/Users/aksle/Downloads/Telegram Desktop/S3_19_Anderson Leong Ke Sheng_Bui Quang Huy_Archive/Wk8/Wk8.srcs/sources_1/new/score_board.v}
  {C:/Users/aksle/Downloads/Telegram Desktop/S3_19_Anderson Leong Ke Sheng_Bui Quang Huy_Archive/Wk8/Wk8.srcs/sources_1/new/single_pulse.v}
  {C:/Users/aksle/Downloads/Telegram Desktop/S3_19_Anderson Leong Ke Sheng_Bui Quang Huy_Archive/Wk8/Wk8.srcs/sources_1/new/win.v}
  {C:/Users/aksle/Downloads/Telegram Desktop/S3_19_Anderson Leong Ke Sheng_Bui Quang Huy_Archive/Wk8/Wk8.srcs/sources_1/new/Top_Student.v}
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/Users/aksle/Downloads/Telegram Desktop/S3_19_Anderson Leong Ke Sheng_Bui Quang Huy_Archive/Wk8/Wk8.srcs/constrs_1/new/Basys3_Master.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/aksle/Downloads/Telegram Desktop/S3_19_Anderson Leong Ke Sheng_Bui Quang Huy_Archive/Wk8/Wk8.srcs/constrs_1/new/Basys3_Master.xdc}}]

set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top Top_Student -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Top_Student.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Top_Student_utilization_synth.rpt -pb Top_Student_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
